
build : basicIf loop simple simpleMethodCall multiplePrint moreComplex   

basicIf:
	gcc basicIf.s -o basicIf

loop:
	gcc loop.s -o loop

simple:
	gcc simple.s -o simple

simpleMethodCall:
	gcc simpleMethodCall.s -o simpleMethodCall

multiplePrint:
	gcc multiplePrint.s -o multiplePrint

moreComplex:
	gcc moreComplex.s -o moreComplex

clean: 
	rm -r moreComplex multiplePrint simpleMethodCall simple loop basicIf 
